server:
  port: 6688 #\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: springcloud-config-demo #\u6307\u5B9A\u670D\u52A1\u540D
  cloud:
    config:
      server:
        git: #\u914D\u7F6Egit\u4ED3\u5E93\u5730\u5740
          uri: http://172.16.55.138:10080/zhangzhijun/itcast-config-server.git