server:
  port: 6688
spring:
  application:
    name: springcloud-config-demo
  cloud:
    config:
      server:
        git:
          uri: http://172.16.55.138:10080/zhangzhijun/itcast-config-server.git